name: FreeHiC
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python=3.6
  - numpy=1.16.*
  - scipy=1.*
  - pysam=0.12.*
  - bx-python=0.8.*
  - cython=0.29.*
  - bedtools
  - samtools
  - bwa
  - pip
  - gcc
